# prometheus.yml
global:
  scrape_interval: 15s # Intervalle pour scrapper les métriques

scrape_configs:
  - job_name: 'backend-metrics' # Nom du job
    static_configs:
      - targets: ['host.docker.internal:5000'] # URL et port du backend
        metrics_path: '/prometheus-metrics' # Chemin pour scraper les métriques
